# name of application
name: git-package

on:
  # Trigger the workflow on push request,
  # but only for the master branch
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        cache: 'npm'

    - name: Install the dependencies 
      run: |
        npm install -g npm-cli-login
        npm-cli-login -u "satishsingh21" -p ${{ secrets.PAT_TOKEN }} -r "https://npm.pkg.github.com"  -e "Satishkumar.Singh@Triconinfotech.com" -s "@satishsingh21"
        npm install

    - name: Release the app
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run semantic-release

