# name of application
name: git-package

on:
  # Trigger the workflow on push request,
  # but only for the master branch
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        cache: 'npm'

    - name: Install the dependencies 
      run: |
        npm install

    - name: Checkout
      uses: actions/checkout@v2

    - name: Semantic Release
      run: |
        - npm install -g npm-cli-login
        - npm-cli-login -u "satishsingh21" -p ${{ secrets.PAT_TOKEN }} -r "https://npm.pkg.github.com" -s "@satishsingh21"
        - npm config set registry "https://npm.pkg.github.com"
        - npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.PAT_TOKEN }}

