# name of application
name: git-package

on:
  # Trigger the workflow on push request,
  # but only for the master branch
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        cache: 'npm'

    - name: Install the dependencies 
      run: |
        npm install -g npm-cli-login
        npm-cli-login -u ${{ secrets.NPM_USERNAME }} -p ${{ secrets.NPM_PASSWORD }} -e ${{ secrets.NPM_EMAIL }} -r ${{ secrets.NPM_REGISTRY }} -s ${{ secrets.NPM_SCOPE }}
        npm config set registry ${{ secrets.NPM_REGISTRY }}
        npm install

    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.PAT_TOKEN }}

